server:
  port: 8080

spring:
  application:
    name: commute-guardian-backend
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/commute_guardian}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cache:
    type: simple
    cache-names:
      - stops
      - routes
      - reliability-metrics

  task:
    scheduling:
      pool:
        size: 5

# MBTA API Configuration
mbta:
  api:
    base-url: ${MBTA_API_BASE:https://api-v3.mbta.com}
    key: ${MBTA_API_KEY:}
    timeout: 30s
    
  gtfs:
    static-url: ${GTFS_STATIC_URL:https://cdn.mbta.com/MBTA_GTFS.zip}
    realtime:
      trip-updates-url: ${GTFS_RT_TRIP_UPDATES_URL:https://cdn.mbta.com/realtime/TripUpdates.pb}
      vehicle-positions-url: ${GTFS_RT_VEHICLE_POSITIONS_URL:https://cdn.mbta.com/realtime/VehiclePositions.pb}
      fetch-interval: ${GTFS_RT_FETCH_INTERVAL:60s}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Reliability Analysis Configuration
reliability:
  analysis:
    on-time-threshold-seconds: 120
    ewma-alpha: 0.3
    min-samples-for-prediction: 10
    risk-bands:
      low-threshold: 0.8
      medium-threshold: 0.6

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.commute.mbta: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: Commute Guardian API
    description: MBTA reliability tracking and leave-now advice service
    version: 1.0.0
    contact:
      name: Commute Guardian Team
